const QUESTIONS = [
// गणित — संख्या पद्धति + बहुपद
{ id:1, subject:"गणित", type:"mcq", marks:1, question:"√2 + √8 का सरल रूप क्या है?", options:["2√2","3√2","√10","4√2"], correct:1 },
{ id:2, subject:"गणित", type:"mcq", marks:1, question:"निम्नलिखित में से कौन-सी संख्या अपरिमेय है?", options:["√49","0.125","√18/3","22/7"], correct:2 },
{ id:3, subject:"गणित", type:"mcq", marks:1, question:"0.272727... का परिमेय रूप क्या है?", options:["3/11","27/100","27/99","11/27"], correct:0 },
{ id:4, subject:"गणित", type:"mcq", marks:1, question:"यदि p(x)=x²−7x+10 है, तो इसका एक शून्यक क्या है?", options:["1","2","−2","5"], correct:1 },
{ id:5, subject:"गणित", type:"mcq", marks:1, question:"p(x)=x²+kx+6 में x+2 गुणनखंड है। k का मान क्या होगा?", options:["−5","5","4","−4"], correct:1 },
{ id:6, subject:"गणित", type:"mcq", marks:1, question:"(2x³−x+1)(x²+3) की घात क्या है?", options:["3","4","5","6"], correct:2 },
{ id:7, subject:"गणित", type:"mcq", marks:1, question:"यदि x−2, p(x)=x³−4x²+ax+6 का गुणनखंड है, तो a क्या है?", options:["−1","0","1","2"], correct:2 },
{ id:8, subject:"गणित", type:"mcq", marks:1, question:"यदि x=√5+√2 और y=√5−√2, तो xy क्या होगा?", options:["3","7","√3","10"], correct:0 },
{ id:9, subject:"गणित", type:"mcq", marks:1, question:"किसी बहुपद p(x) के लिए p(3)=0 है। निश्चित रूप से कौन-सा कथन सही है?", options:["x+3 गुणनखंड है","x−3 गुणनखंड है","3x गुणनखंड है","p(0)=0"], correct:1 },
{ id:10, subject:"गणित", type:"mcq", marks:1, question:"यदि 0.125 को p/q के रूप में लिखा जाए जहाँ q≠0, तो एक सरल रूप क्या है?", options:["1/8","1/6","1/4","125/10"], correct:0 },
{ id:11, subject:"गणित", type:"subjective", marks:4, question:"सिद्ध कीजिए कि √3 एक अपरिमेय संख्या है। विरोधाभास विधि के मुख्य चरण स्पष्ट कीजिए।" },
{ id:12, subject:"गणित", type:"subjective", marks:4, question:"p(x)=2x²−5x−3 के शून्यक ज्ञात कीजिए तथा शून्यकों के योग और गुणनफल को बहुपद के गुणांकों से सत्यापित कीजिए।" },

// विज्ञान — हमारे आसपास के पदार्थ + पदार्थ शुद्ध हैं?
{ id:13, subject:"विज्ञान", type:"mcq", marks:1, question:"समान मात्रा के पानी में वाष्पीकरण सबसे तेज किस स्थिति में होगा?", options:["ठंडी, बंद जगह","गर्म, हवादार और चौड़े मुँह वाले बर्तन में","अधिक आर्द्रता में","ढके हुए बर्तन में"], correct:1 },
{ id:14, subject:"विज्ञान", type:"mcq", marks:1, question:"गैस को दबाने पर उसके कणों के बीच की दूरी सामान्यतः:", options:["घटती है","बढ़ती है","समान रहती है","शून्य हो जाती है"], correct:0 },
{ id:15, subject:"विज्ञान", type:"mcq", marks:1, question:"निम्न में से समांगी मिश्रण कौन-सा है?", options:["रेत और पानी","तेल और पानी","नमक का जलीय विलयन","मिट्टी और पानी"], correct:2 },
{ id:16, subject:"विज्ञान", type:"mcq", marks:1, question:"रेत, नमक और अमोनियम क्लोराइड के मिश्रण को अलग करते समय पहले कौन-सी विधि उपयोगी होगी?", options:["निस्यंदन","उर्ध्वपातन","अपकेंद्रण","अवसादन"], correct:1 },
{ id:17, subject:"विज्ञान", type:"mcq", marks:1, question:"निम्न में से किसमें टिंडल प्रभाव अपेक्षित है?", options:["नमक का विलयन","चीनी का विलयन","दूध","आसुत जल"], correct:2 },
{ id:18, subject:"विज्ञान", type:"mcq", marks:1, question:"दो द्रवों के क्वथनांक में पर्याप्त अंतर हो तो उन्हें अलग करने की उपयुक्त विधि है:", options:["निस्यंदन","आसवन","उर्ध्वपातन","अवसादन"], correct:1 },
{ id:19, subject:"विज्ञान", type:"mcq", marks:1, question:"निलंबन की कौन-सी विशेषता सही है?", options:["कण हमेशा अदृश्य रहते हैं","कण समय के साथ बैठ सकते हैं","इसे निस्यंदित नहीं किया जा सकता","यह हमेशा पारदर्शी होता है"], correct:1 },
{ id:20, subject:"विज्ञान", type:"mcq", marks:1, question:"कपड़ों को फैलाकर सुखाने से वे जल्दी सूखते हैं मुख्यतः क्योंकि:", options:["सतह क्षेत्र बढ़ता है","द्रव्यमान बढ़ता है","आर्द्रता बढ़ती है","तापमान शून्य होता है"], correct:0 },
{ id:21, subject:"विज्ञान", type:"mcq", marks:1, question:"क्रोमैटोग्राफी का उपयोग मुख्यतः किस प्रकार के मिश्रण के घटकों को अलग करने में किया जाता है?", options:["रंगों/स्याही के विभिन्न घटक","रेत और पत्थर","लोहा और सल्फर","पानी और रेत"], correct:0 },
{ id:22, subject:"विज्ञान", type:"subjective", marks:4, question:"वाष्पीकरण को प्रभावित करने वाले चार कारकों को उदाहरण सहित समझाइए।" },
{ id:23, subject:"विज्ञान", type:"subjective", marks:4, question:"विलयन, कोलाइड और निलंबन में कणों के आकार, स्थायित्व, टिंडल प्रभाव और निस्यंदन के आधार पर अंतर स्पष्ट कीजिए।" },

// सामाजिक विज्ञान — भौगोलिक खोजें + अमेरिकी स्वतंत्रता संग्राम + स्थिति एवं विस्तार
{ id:24, subject:"सामाजिक विज्ञान", type:"mcq", marks:1, question:"भारत के लिए समुद्री मार्ग की खोज से यूरोपीय शक्तियों की भारत में रुचि क्यों बढ़ी?", options:["समुद्री व्यापार से व्यापारिक लाभ और नियंत्रण की संभावना बढ़ी","भारत में खेती समाप्त हो गई","स्थलमार्ग पूरी तरह बंद हो गए","यूरोप ने एशिया से संपर्क बंद कर दिया"], correct:0 },
{ id:25, subject:"सामाजिक विज्ञान", type:"mcq", marks:1, question:"बोस्टन टी पार्टी मुख्यतः किसके विरोध से जुड़ी थी?", options:["चाय पर कर और ईस्ट इंडिया कंपनी को मिली विशेष व्यापारिक छूट","कृषि भूमि कर","शिक्षा कर","धार्मिक कर"], correct:0 },
{ id:26, subject:"सामाजिक विज्ञान", type:"mcq", marks:1, question:"अमेरिकी स्वतंत्रता की घोषणा किस वर्ष हुई?", options:["1773","1776","1781","1783"], correct:1 },
{ id:27, subject:"सामाजिक विज्ञान", type:"mcq", marks:1, question:"अमेरिकी उपनिवेशों का 'प्रतिनिधित्व के बिना कराधान नहीं' जैसा विरोध किस मूल समस्या को दर्शाता था?", options:["राजनीतिक प्रतिनिधित्व की कमी","कृषि उत्पादन की कमी","भाषाई समस्या","भौगोलिक विस्तार"], correct:0 },
{ id:28, subject:"सामाजिक विज्ञान", type:"mcq", marks:1, question:"भारत का मानक मध्याह्न किस देशांतर पर आधारित है?", options:["68°7′E","82°30′E","97°25′E","23°30′N"], correct:1 },
{ id:29, subject:"सामाजिक विज्ञान", type:"mcq", marks:1, question:"15° देशांतर का अंतर स्थानीय समय में लगभग कितना अंतर पैदा करता है?", options:["15 मिनट","30 मिनट","1 घंटा","2 घंटे"], correct:2 },
{ id:30, subject:"सामाजिक विज्ञान", type:"mcq", marks:1, question:"82°30′E से 7°30′ पश्चिम स्थित स्थान का स्थानीय समय लगभग कितना पीछे होगा?", options:["15 मिनट","30 मिनट","1 घंटा","2 घंटे"], correct:2 },
{ id:31, subject:"सामाजिक विज्ञान", type:"mcq", marks:1, question:"भारत की उत्तर दिशा में कौन-सी प्रमुख भौगोलिक विशेषता प्राकृतिक सीमा का कार्य करती है?", options:["हिमालय","अरब सागर","हिंद महासागर","दक्कन का पठार"], correct:0 },
{ id:32, subject:"सामाजिक विज्ञान", type:"mcq", marks:1, question:"भारत की पूर्व-पश्चिम देशांतर सीमा के कारण किस समस्या को मानक समय अपनाकर कम किया जाता है?", options:["स्थानीय समय के अंतर की प्रशासनिक कठिनाई","मानसून की समस्या","अक्षांश का अंतर","भाषाओं की विविधता"], correct:0 },
{ id:33, subject:"सामाजिक विज्ञान", type:"subjective", marks:4, question:"भौगोलिक खोजों के तीन प्रमुख परिणाम लिखिए और उनके आर्थिक या राजनीतिक प्रभाव समझाइए।" },
{ id:34, subject:"सामाजिक विज्ञान", type:"subjective", marks:4, question:"अमेरिकी स्वतंत्रता संग्राम के प्रमुख कारणों को कराधान, राजनीतिक अधिकार और उपनिवेशवादी नियंत्रण के संदर्भ में समझाइए।" },

// हिन्दी — कहानी का प्लॉट + नालंदा + रैदास + बिहार का लोकगायन + अपठित गद्यांश
{ id:35, subject:"हिन्दी", type:"mcq", marks:1, question:"'कहानी का प्लॉट' में मुंशीजी के बड़े भाई कौन थे?", options:["पुलिस दारोगा","शिक्षक","व्यापारी","जमींदार"], correct:0 },
{ id:36, subject:"हिन्दी", type:"mcq", marks:1, question:"कहानी में परिवार की पुरानी प्रतिष्ठा और बाद की आर्थिक स्थिति का अंतर किस बात को उभारता है?", options:["आर्थिक परिवर्तन का मानवीय प्रभाव","नालंदा का इतिहास","लोकगायन की परंपरा","वैज्ञानिक विकास"], correct:0 },
{ id:37, subject:"हिन्दी", type:"mcq", marks:1, question:"नालंदा की प्रसिद्धि का प्रमुख आधार क्या था?", options:["अंतरराष्ट्रीय ज्ञान और शिक्षा का केंद्र होना","केवल सैनिक प्रशिक्षण","केवल व्यापार","केवल उत्सव"], correct:0 },
{ id:38, subject:"हिन्दी", type:"mcq", marks:1, question:"रैदास के पदों में चंदन और पानी का संबंध किस भाव को व्यक्त करता है?", options:["भय","भक्त और भगवान की आत्मीयता","क्रोध","वियोग"], correct:1 },
{ id:39, subject:"हिन्दी", type:"mcq", marks:1, question:"बिहार के लोकगायन की प्रमुख विशेषता क्या है?", options:["लोकजीवन और परंपराओं से जुड़ाव","केवल दरबारी संगीत","केवल विदेशी प्रभाव","केवल वाद्य-संगीत"], correct:0 },
{ id:40, subject:"हिन्दी", type:"mcq", marks:1, question:"लोकगायन किसी समाज की संस्कृति को सुरक्षित रखने में कैसे सहायक हो सकता है?", options:["परंपराओं और सामुदायिक अनुभवों को पीढ़ियों तक पहुँचाकर","सभी स्थानीय भाषाएँ समाप्त करके","केवल लिखित इतिहास को बदलकर","केवल मनोरंजन करके"], correct:0 },
{ id:41, subject:"हिन्दी", type:"mcq", marks:1, section:"अपठित गद्यांश", passage:"एक छोटे गाँव के विद्यालय में पुस्तकालय था, लेकिन नई पुस्तकें बहुत कम थीं। आरव ने शिक्षक से बात की और परिवारों से पुरानी उपयोगी पुस्तकें एकत्र करने का सुझाव दिया। शिक्षक के सहयोग से पुस्तकें विषयवार व्यवस्थित की गईं और शनिवार को पठन समय शुरू हुआ। कुछ सप्ताह बाद बच्चों में पढ़ने की रुचि बढ़ने लगी। आरव ने समझा कि किसी समस्या पर केवल शिकायत करने के बजाय छोटा, व्यवस्थित और सामूहिक प्रयास भी परिवर्तन ला सकता है।", question:"आरव की पहल का सबसे महत्वपूर्ण आधार क्या था?", options:["समस्या की पहचान और सामूहिक सहयोग","केवल धन खर्च करना","खेल का समय बढ़ाना","पुस्तकें बेचना"], correct:0 },
{ id:42, subject:"हिन्दी", type:"mcq", marks:1, section:"अपठित गद्यांश", passage:"एक छोटे गाँव के विद्यालय में पुस्तकालय था, लेकिन नई पुस्तकें बहुत कम थीं। आरव ने शिक्षक से बात की और परिवारों से पुरानी उपयोगी पुस्तकें एकत्र करने का सुझाव दिया। शिक्षक के सहयोग से पुस्तकें विषयवार व्यवस्थित की गईं और शनिवार को पठन समय शुरू हुआ। कुछ सप्ताह बाद बच्चों में पढ़ने की रुचि बढ़ने लगी। आरव ने समझा कि किसी समस्या पर केवल शिकायत करने के बजाय छोटा, व्यवस्थित और सामूहिक प्रयास भी परिवर्तन ला सकता है।", question:"गद्यांश से कौन-सा निष्कर्ष निकाला जा सकता है?", options:["संगठन और सहयोग छोटे प्रयास को प्रभावी बना सकते हैं","हर समस्या के लिए बड़ी राशि चाहिए","पुस्तकालय केवल शिक्षकों के लिए है","पठन समय से कोई लाभ नहीं होता"], correct:0 },
{ id:43, subject:"हिन्दी", type:"mcq", marks:1, question:"'नालंदा' जैसे ज्ञान-केंद्र की सबसे महत्वपूर्ण विशेषता क्या मानी जा सकती है?", options:["विचार और ज्ञान का व्यापक आदान-प्रदान","केवल व्यापार","केवल युद्धाभ्यास","केवल मनोरंजन"], correct:0 },
{ id:44, subject:"हिन्दी", type:"subjective", marks:4, section:"अपठित गद्यांश", passage:"एक छोटे गाँव के विद्यालय में पुस्तकालय था, लेकिन नई पुस्तकें बहुत कम थीं। आरव ने शिक्षक से बात की और परिवारों से पुरानी उपयोगी पुस्तकें एकत्र करने का सुझाव दिया। शिक्षक के सहयोग से पुस्तकें विषयवार व्यवस्थित की गईं और शनिवार को पठन समय शुरू हुआ। कुछ सप्ताह बाद बच्चों में पढ़ने की रुचि बढ़ने लगी। आरव ने समझा कि किसी समस्या पर केवल शिकायत करने के बजाय छोटा, व्यवस्थित और सामूहिक प्रयास भी परिवर्तन ला सकता है।", question:"80–100 शब्दों में लिखिए कि आरव ने विद्यालय की समस्या को उपयोगी पहल में कैसे बदला और उसके प्रयास की दो प्रमुख विशेषताएँ बताइए।" },

// संस्कृत — ईशस्तुति + लोभविष्टः चक्रधरः
{ id:45, subject:"संस्कृत", type:"mcq", marks:1, question:"'ईशस्तुतिः' का प्रमुख भाव क्या है?", options:["भक्ति और श्रद्धा","ईर्ष्या","उपेक्षा","प्रतिशोध"], correct:0 },
{ id:46, subject:"संस्कृत", type:"mcq", marks:1, question:"'लोभविष्टः' शब्द का अर्थ क्या है?", options:["लोभ से ग्रस्त","भय से मुक्त","ज्ञान से पूर्ण","क्रोध से रहित"], correct:0 },
{ id:47, subject:"संस्कृत", type:"mcq", marks:1, question:"'लोभविष्टः चक्रधरः' कथा का प्रमुख संदेश क्या है?", options:["लोभ से विवेक प्रभावित हो सकता है","धन ही सर्वोच्च है","जोखिम हमेशा सफलता देता है","ज्ञान अनावश्यक है"], correct:0 },
{ id:48, subject:"संस्कृत", type:"mcq", marks:1, question:"'ईशस्तुतिः' में भक्त की कौन-सी भावना प्रमुख है?", options:["समर्पण","ईर्ष्या","अवज्ञा","घृणा"], correct:0 },
{ id:49, subject:"संस्कृत", type:"mcq", marks:1, question:"कथा के शीर्षक में 'लोभविष्टः' किस चरित्रगत दोष की ओर संकेत करता है?", options:["लोभ","विनय","करुणा","धैर्य"], correct:0 },
{ id:50, subject:"संस्कृत", type:"mcq", marks:1, question:"ईश्वर की स्तुति करने से भक्त के मन में कौन-सा भाव मजबूत होता है?", options:["श्रद्धा और आत्मसमर्पण","ईर्ष्या","अहंकार","प्रतिशोध"], correct:0 },
{ id:51, subject:"संस्कृत", type:"mcq", marks:1, question:"लोभ के कारण निर्णय लेते समय किस गुण की आवश्यकता सबसे अधिक होती है?", options:["विवेक","अहंकार","असंयम","उपेक्षा"], correct:0 },
{ id:52, subject:"संस्कृत", type:"mcq", marks:1, question:"'चक्रधरः' शब्द किसका नाम है?", options:["कथा के पात्र का","स्थान का","नदी का","पर्वत का"], correct:0 },
{ id:53, subject:"संस्कृत", type:"subjective", marks:4, question:"'लोभविष्टः चक्रधरः' के आधार पर स्पष्ट कीजिए कि लोभ मनुष्य के विवेक और निर्णयों को कैसे प्रभावित करता है।" },

// English — literature + reading
{ id:54, subject:"English", type:"mcq", marks:1, question:"In 'I'm going to dance again', Sonal Mansingh mainly represents:", options:["resilience and determination","fear and avoidance","dependence on fame","indifference"], correct:0 },
{ id:55, subject:"English", type:"mcq", marks:1, question:"In 'Scaling Great Heights', Santosh Yadav is remembered for:", options:["climbing Mount Everest twice","avoiding mountains","becoming a swimmer","working only as a teacher"], correct:0 },
{ id:56, subject:"English", type:"mcq", marks:1, question:"In 'Dharam Juddha', Padma's struggle is closely connected with:", options:["education, dignity and identity","wealth only","political power","travel"], correct:0 },
{ id:57, subject:"English", type:"mcq", marks:1, question:"In 'The Grandmother', the speaker's remembrance is mainly shaped by:", options:["memory and sensory impressions","a newspaper report","a scientific experiment","an examination"], correct:0 },
{ id:58, subject:"English", type:"mcq", marks:1, section:"Reading Comprehension", passage:"Meera noticed that children in her new neighbourhood had to travel far to borrow books. She collected unused books from families, arranged them in a small room and recorded borrowed books in a notebook. At first only a few children came, but she continued inviting them and involved older students. After several months the room became a lively reading corner. Meera learned that a good idea also needs patience, organisation and cooperation.", question:"Why did Meera record borrowed books?", options:["To organise the reading corner","To sell the books","To prepare for a sports event","To decorate her room"], correct:0 },
{ id:59, subject:"English", type:"mcq", marks:1, section:"Reading Comprehension", passage:"Meera noticed that children in her new neighbourhood had to travel far to borrow books. She collected unused books from families, arranged them in a small room and recorded borrowed books in a notebook. At first only a few children came, but she continued inviting them and involved older students. After several months the room became a lively reading corner. Meera learned that a good idea also needs patience, organisation and cooperation.", question:"Which quality was NOT necessary for Meera's success?", options:["Patience","Organisation","Cooperation","Giving up quickly"], correct:3 },
{ id:60, subject:"English", type:"mcq", marks:1, question:"The main lesson of Meera's experience is that:", options:["good ideas need organised effort and cooperation","good ideas succeed automatically","only money creates change","problems should be ignored"], correct:0 },
{ id:61, subject:"English", type:"mcq", marks:1, question:"The word 'resilience' is closest in meaning to:", options:["ability to recover and continue","fear of failure","carelessness","confusion"], correct:0 },
{ id:62, subject:"English", type:"subjective", marks:4, question:"In about 80–100 words, explain how Sonal Mansingh's determination helps her respond to a major setback. Refer to her attitude and willingness to continue." },

// Reasoning — Number Series
{ id:63, subject:"तार्किक क्षमता", type:"mcq", marks:1, question:"शृंखला पूरी करें: 2, 6, 12, 20, 30, ?", options:["40","42","44","46"], correct:1 },
{ id:64, subject:"तार्किक क्षमता", type:"mcq", marks:1, question:"शृंखला पूरी करें: 3, 8, 18, 38, 78, ?", options:["156","158","159","160"], correct:2 },
{ id:65, subject:"तार्किक क्षमता", type:"mcq", marks:1, question:"शृंखला पूरी करें: 121, 100, 81, 64, ?", options:["49","45","36","56"], correct:0 },
{ id:66, subject:"तार्किक क्षमता", type:"mcq", marks:1, question:"शृंखला पूरी करें: 2, 3, 5, 9, 17, ?", options:["25","31","33","35"], correct:2 },
{ id:67, subject:"तार्किक क्षमता", type:"mcq", marks:1, question:"शृंखला पूरी करें: 4, 9, 19, 39, 79, ?", options:["149","157","159","161"], correct:2 },
{ id:68, subject:"तार्किक क्षमता", type:"mcq", marks:1, question:"शृंखला पूरी करें: 1, 4, 10, 22, 46, ?", options:["82","90","94","96"], correct:2 },
{ id:69, subject:"तार्किक क्षमता", type:"mcq", marks:1, question:"शृंखला पूरी करें: 5, 10, 20, 40, 80, ?", options:["120","140","160","180"], correct:2 },
{ id:70, subject:"तार्किक क्षमता", type:"subjective", marks:4, question:"किसी एक संख्या-शृंखला के नियम को उदाहरण सहित समझाइए और बताइए कि शृंखला में अगला पद निर्धारित करने के लिए आप किन चरणों का पालन करेंगे।" }
];