const QUESTIONS = [
// गणित — संख्या पद्धति + बहुपद
{ id:1, subject:"गणित", type:"mcq", marks:1, question:"यदि x = 1/(√3 + √2), तो x का परिमेयीकृत रूप क्या होगा?", options:["√3 + √2","√3 − √2","1/(√3 − √2)","√5"], correct:1 },
{ id:2, subject:"गणित", type:"mcq", marks:1, question:"निम्न में से किस संख्या का दशमलव प्रसार अनंत और अनावर्ती होगा?", options:["7/8","13/40","√5","11/20"], correct:2 },
{ id:3, subject:"गणित", type:"mcq", marks:1, question:"यदि p(x)=x²−7x+10 है, तो x=2 रखने पर p(x) का मान क्या प्राप्त होता है और इससे क्या निष्कर्ष निकलेगा?", options:["0; x−2 गुणनखंड है","2; x−2 गुणनखंड है","0; x+2 गुणनखंड है","4; x−2 गुणनखंड है"], correct:0 },
{ id:4, subject:"गणित", type:"mcq", marks:1, question:"बहुपद p(x)=x²+kx+6 में x+2 गुणनखंड है। यदि p(−2)=0 का प्रयोग करें, तो k का मान क्या होगा?", options:["−5","5","4","−4"], correct:1 },
{ id:5, subject:"गणित", type:"mcq", marks:1, question:"दो बहुपदों की घात क्रमशः 3 और 2 है। उनके गुणनफल की घात, यदि अग्रणी गुणांक शून्य नहीं हैं, क्या होगी?", options:["1","5","6","अधिकतम 3"], correct:1 },
{ id:6, subject:"गणित", type:"mcq", marks:1, question:"यदि x−2, p(x)=x³−4x²+ax+6 का गुणनखंड है, तो p(2)=0 की सहायता से a ज्ञात कीजिए।", options:["−1","0","1","2"], correct:2 },
{ id:7, subject:"गणित", type:"subjective", marks:4, question:"√10 को संख्या रेखा पर निरूपित करने की रचना विधि क्रमबद्ध चरणों में समझाइए। प्रत्येक रचना-चरण के पीछे प्रयुक्त ज्यामितीय विचार भी लिखिए।" },
{ id:8, subject:"गणित", type:"subjective", marks:4, question:"सिद्ध कीजिए कि √3 एक अपरिमेय संख्या है। विरोधाभास विधि अपनाते हुए यह भी स्पष्ट कीजिए कि प्राप्त विरोधाभास क्यों उत्पन्न होता है।" },
{ id:9, subject:"गणित", type:"subjective", marks:4, question:"p(x)=2x²−5x−3 के शून्यक ज्ञात कीजिए। फिर शून्यकों के योग और गुणनफल को क्रमशः −b/a और c/a से मिलाकर सत्यापित कीजिए।" },

// विज्ञान — हमारे आसपास के पदार्थ + पदार्थ शुद्ध हैं?
{ id:10, subject:"विज्ञान", type:"mcq", marks:1, question:"एक विद्यार्थी समान मात्रा के पानी को धूप में एक चौड़े बर्तन और एक संकीर्ण बर्तन में रखता है। चौड़े बर्तन का पानी पहले सूखता है। इसका मुख्य कारण क्या है?", options:["चौड़े बर्तन में पानी का द्रव्यमान कम होता है","चौड़े बर्तन में सतह क्षेत्र अधिक होता है","चौड़े बर्तन में पानी का क्वथनांक अधिक होता है","संकीर्ण बर्तन में कण स्थिर रहते हैं"], correct:1 },
{ id:11, subject:"विज्ञान", type:"mcq", marks:1, question:"एक सिरिंज में हवा भरकर उसका मुँह बंद कर दिया गया। पिस्टन दबाने पर हवा का आयतन घटता है। यह किस तथ्य को दर्शाता है?", options:["गैस के कणों के बीच रिक्त स्थान होता है","गैस के कणों का द्रव्यमान नहीं होता","गैस के कण बिल्कुल स्थिर होते हैं","गैस में कोई आकर्षण नहीं होता"], correct:0 },
{ id:12, subject:"विज्ञान", type:"mcq", marks:1, question:"किस नमूने को देखकर आप सबसे उचित रूप से कहेंगे कि वह समांगी मिश्रण है?", options:["रेत और पानी","तेल और पानी","पूरी तरह घुला नमक का विलयन","मिट्टी और पानी"], correct:2 },
{ id:13, subject:"विज्ञान", type:"mcq", marks:1, question:"रेत, नमक और अमोनियम क्लोराइड के मिश्रण से तीनों पदार्थ अलग करने हैं। सबसे पहले कौन-सा गुण उपयोग करना उचित होगा?", options:["अमोनियम क्लोराइड की उर्ध्वपातन क्षमता","नमक की चुंबकीय प्रकृति","रेत का वाष्पीकरण","पानी की निस्यंदन क्षमता"], correct:0 },
{ id:14, subject:"विज्ञान", type:"mcq", marks:1, question:"एक प्रकाश-किरण दूध से गुजरते समय स्पष्ट दिखाई देती है, जबकि नमक के साफ विलयन में उसका पथ दिखाई नहीं देता। इससे क्या निष्कर्ष निकलता है?", options:["दूध कोलॉइडल है और नमक का विलयन सच्चा विलयन है","दूध सच्चा विलयन है और नमक कोलॉइड है","दोनों शुद्ध पदार्थ हैं","दोनों निलंबन हैं"], correct:0 },
{ id:15, subject:"विज्ञान", type:"mcq", marks:1, question:"किसी मिश्रण में दो मिश्रणीय द्रवों के क्वथनांकों में पर्याप्त अंतर है। अलग करने के लिए कौन-सी विधि सबसे उपयुक्त है?", options:["आसवन","निस्यंदन","अवसादन","उर्ध्वपातन"], correct:0 },
{ id:16, subject:"विज्ञान", type:"subjective", marks:4, question:"वाष्पीकरण की दर पर तापमान, सतह क्षेत्र, वायु की गति और आर्द्रता के प्रभाव को समझाइए। उत्तर में रोजमर्रा के जीवन के कम-से-कम दो उदाहरण दीजिए।" },
{ id:17, subject:"विज्ञान", type:"subjective", marks:4, question:"विलयन, कोलॉइड और निलंबन की तुलना कणों के आकार/दृश्यता, स्थायित्व, टिंडल प्रभाव और निस्यंदन के आधार पर कीजिए। अंत में प्रत्येक का एक उदाहरण दीजिए।" },

// सामाजिक विज्ञान — भौगोलिक खोजें + अमेरिकी स्वतंत्रता संग्राम + स्थिति एवं विस्तार
{ id:18, subject:"सामाजिक विज्ञान", type:"mcq", marks:1, question:"भारत के लिए समुद्री मार्ग मिलने के बाद यूरोपीय शक्तियों ने भारत में व्यापारिक गतिविधियाँ बढ़ाईं। इसका सबसे तार्किक कारण क्या था?", options:["समुद्री मार्ग ने दूरस्थ बाजारों तक सीधे पहुँच आसान की","भारत का स्थलरूप समाप्त हो गया","यूरोप में खेती बंद हो गई","भारत में सभी स्थानीय व्यापार समाप्त हो गए"], correct:0 },
{ id:19, subject:"सामाजिक विज्ञान", type:"mcq", marks:1, question:"बोस्टन टी पार्टी को केवल 'चाय की घटना' मानना अधूरा क्यों होगा?", options:["यह कराधान और उपनिवेशों के राजनीतिक अधिकारों के विवाद से जुड़ी थी","यह केवल मौसम की समस्या थी","यह कृषि उत्पादन का आंदोलन था","यह धार्मिक उत्सव था"], correct:0 },
{ id:20, subject:"सामाजिक विज्ञान", type:"mcq", marks:1, question:"यदि कोई उपनिवेश बाहरी सत्ता को कर दे, लेकिन कर लगाने के निर्णय में उसका प्रतिनिधित्व न हो, तो मुख्य आपत्ति किस विचार से जुड़ती है?", options:["प्रतिनिधित्व के बिना कराधान का विरोध","व्यापार का पूर्ण निषेध","राजा की शक्ति का समर्थन","कृषि सुधार"], correct:0 },
{ id:21, subject:"सामाजिक विज्ञान", type:"mcq", marks:1, question:"82°30′E को भारत का मानक मध्याह्न मानने का व्यावहारिक लाभ क्या है?", options:["देश के लिए एक समान मानक समय निर्धारित किया जा सकता है","भारत में स्थानीय समय समाप्त हो जाता है","सूर्योदय हर जगह एक ही समय पर होता है","देशांतर का प्रभाव समाप्त हो जाता है"], correct:0 },
{ id:22, subject:"सामाजिक विज्ञान", type:"mcq", marks:1, question:"82°30′E से 15° पूर्व स्थित स्थान का स्थानीय समय लगभग कितना आगे होगा?", options:["30 मिनट","1 घंटा","2 घंटे","15 मिनट"], correct:1 },
{ id:23, subject:"सामाजिक विज्ञान", type:"mcq", marks:1, question:"भारत की पूर्व-पश्चिम देशांतर सीमा बड़ी होने पर स्थानीय समय में अंतर क्यों बढ़ता है?", options:["पृथ्वी के 360° घूर्णन को 24 घंटे में पूरा करने के कारण देशांतर बदलने पर स्थानीय समय बदलता है","अक्षांश बदलने से हर जगह दिन समाप्त हो जाता है","समुद्र स्थानीय समय तय करता है","मानक समय देशांतर को बदल देता है"], correct:0 },
{ id:24, subject:"सामाजिक विज्ञान", type:"subjective", marks:4, question:"भौगोलिक खोजों के तीन प्रमुख परिणामों का वर्णन कीजिए। प्रत्येक परिणाम को व्यापार, उपनिवेशवाद या राजनीतिक शक्ति में आए परिवर्तन से जोड़कर समझाइए।" },
{ id:25, subject:"सामाजिक विज्ञान", type:"subjective", marks:4, question:"अमेरिकी स्वतंत्रता संग्राम के कारणों को कराधान, प्रतिनिधित्व और उपनिवेशवादी नियंत्रण के संदर्भ में समझाइए। फिर बताइए कि स्वतंत्रता की घोषणा ने संघर्ष को वैचारिक आधार कैसे दिया।" },

// हिन्दी — कहानी का प्लॉट + नालंदा + रैदास + बिहार का लोकगायन + अपठित गद्यांश
{ id:26, subject:"हिन्दी", type:"mcq", marks:1, question:"'कहानी का प्लॉट' में मुंशीजी के बड़े भाई का पुलिस दारोगा होना कहानी में किस विरोधाभास को समझने में सहायक है?", options:["परिवार की पुरानी सामाजिक स्थिति और बाद की आर्थिक विवशता का अंतर","मुंशीजी की शिक्षा और नालंदा का संबंध","गाँव के कृषि उत्पादन और लोकगायन का संबंध","पुलिस व्यवस्था और समुद्री व्यापार का संबंध"], correct:0 },
{ id:27, subject:"हिन्दी", type:"mcq", marks:1, question:"नालंदा को केवल एक भवन या मठ मानना उसके महत्व को कम करके आँकना क्यों होगा?", options:["वह व्यापक ज्ञान-अध्ययन और विद्वानों के आदान-प्रदान का केंद्र था","वह केवल सैनिक छावनी था","वह केवल समुद्री बंदरगाह था","वह केवल राजकीय कर-संग्रह केंद्र था"], correct:0 },
{ id:28, subject:"हिन्दी", type:"mcq", marks:1, question:"रैदास के पदों में 'चंदन' और 'पानी' का संबंध भक्त और भगवान के रिश्ते की किस विशेषता को उभारता है?", options:["दूरी","अभिन्न आत्मीयता","प्रतिस्पर्धा","भय"], correct:1 },
{ id:29, subject:"हिन्दी", type:"mcq", marks:1, question:"बिहार के लोकगायन का महत्व केवल मनोरंजन तक सीमित नहीं है, क्योंकि वह:", options:["लोकजीवन, परंपरा और सामुदायिक अनुभवों को संरक्षित और व्यक्त करता है","केवल दरबारों में गाया जाता है","केवल विदेशी संगीत पर आधारित है","केवल वाद्ययंत्रों का प्रदर्शन है"], correct:0 },
{ id:30, subject:"हिन्दी", type:"mcq", marks:1, section:"अपठित गद्यांश", passage:`एक छोटे से गाँव में आरव नाम का विद्यार्थी रहता था। उसके विद्यालय में पुस्तकालय तो था, लेकिन वहाँ नई पुस्तकें बहुत कम थीं। आरव ने देखा कि कई बच्चे खाली समय में केवल खेलते रहते थे और पढ़ने की आदत धीरे-धीरे कम होती जा रही थी। उसने अपने शिक्षक से बात की और पुराने समाचार-पत्र, पत्रिकाएँ तथा उपयोगी पुस्तकें एकत्र करने का सुझाव दिया। शिक्षक ने गाँव के लोगों से सहयोग माँगा। कुछ ही सप्ताह में अनेक परिवारों ने अपने घर की ऐसी पुस्तकें दान कर दीं जिन्हें वे अब नहीं पढ़ते थे। आरव और उसके साथियों ने पुस्तकों को विषय के अनुसार व्यवस्थित किया और प्रत्येक शनिवार को एक घंटे का 'पठन समय' शुरू किया। धीरे-धीरे बच्चों में पढ़ने की रुचि बढ़ने लगी। आरव ने समझा कि किसी समस्या को देखकर केवल शिकायत करना पर्याप्त नहीं है; छोटे लेकिन व्यवस्थित प्रयास से भी सकारात्मक परिवर्तन लाया जा सकता है।`, question:"गद्यांश में आरव की पहल को प्रभावी बनाने वाला कारण कौन-सा था?", options:["उसने समस्या पहचानी, सहयोग जुटाया और व्यवस्था बनाई","उसने केवल नई पुस्तकें खरीदने पर जोर दिया","उसने पुस्तकालय बंद कर दिया","उसने बच्चों का खेल का समय समाप्त कर दिया"], correct:0 },
{ id:31, subject:"हिन्दी", type:"mcq", marks:1, section:"अपठित गद्यांश", passage:`एक छोटे से गाँव में आरव नाम का विद्यार्थी रहता था। उसके विद्यालय में पुस्तकालय तो था, लेकिन वहाँ नई पुस्तकें बहुत कम थीं। आरव ने देखा कि कई बच्चे खाली समय में केवल खेलते रहते थे और पढ़ने की आदत धीरे-धीरे कम होती जा रही थी। उसने अपने शिक्षक से बात की और पुराने समाचार-पत्र, पत्रिकाएँ तथा उपयोगी पुस्तकें एकत्र करने का सुझाव दिया। शिक्षक ने गाँव के लोगों से सहयोग माँगा। कुछ ही सप्ताह में अनेक परिवारों ने अपने घर की ऐसी पुस्तकें दान कर दीं जिन्हें वे अब नहीं पढ़ते थे। आरव और उसके साथियों ने पुस्तकों को विषय के अनुसार व्यवस्थित किया और प्रत्येक शनिवार को एक घंटे का 'पठन समय' शुरू किया। धीरे-धीरे बच्चों में पढ़ने की रुचि बढ़ने लगी। आरव ने समझा कि किसी समस्या को देखकर केवल शिकायत करना पर्याप्त नहीं है; छोटे लेकिन व्यवस्थित प्रयास से भी सकारात्मक परिवर्तन लाया जा सकता है।`, question:"यदि गाँव के लोगों ने सहयोग न किया होता, तो पहल के किस हिस्से पर सबसे अधिक प्रभाव पड़ता?", options:["पुस्तकों का संग्रह और समुदाय-आधारित विस्तार","आरव की पढ़ने की इच्छा","विद्यालय का भवन","शनिवार नामक दिन"], correct:0 },
{ id:32, subject:"हिन्दी", type:"subjective", marks:4, question:"'कहानी का प्लॉट' के आधार पर स्पष्ट कीजिए कि आर्थिक स्थिति में परिवर्तन व्यक्ति के व्यवहार और पारिवारिक संबंधों को कैसे प्रभावित कर सकता है। उत्तर को कहानी के प्रसंग से जोड़िए।" },
{ id:33, subject:"हिन्दी", type:"subjective", marks:4, section:"अपठित गद्यांश", passage:`एक छोटे से गाँव में आरव नाम का विद्यार्थी रहता था। उसके विद्यालय में पुस्तकालय तो था, लेकिन वहाँ नई पुस्तकें बहुत कम थीं। आरव ने देखा कि कई बच्चे खाली समय में केवल खेलते रहते थे और पढ़ने की आदत धीरे-धीरे कम होती जा रही थी। उसने अपने शिक्षक से बात की और पुराने समाचार-पत्र, पत्रिकाएँ तथा उपयोगी पुस्तकें एकत्र करने का सुझाव दिया। शिक्षक ने गाँव के लोगों से सहयोग माँगा। कुछ ही सप्ताह में अनेक परिवारों ने अपने घर की ऐसी पुस्तकें दान कर दीं जिन्हें वे अब नहीं पढ़ते थे। आरव और उसके साथियों ने पुस्तकों को विषय के अनुसार व्यवस्थित किया और प्रत्येक शनिवार को एक घंटे का 'पठन समय' शुरू किया। धीरे-धीरे बच्चों में पढ़ने की रुचि बढ़ने लगी। आरव ने समझा कि किसी समस्या को देखकर केवल शिकायत करना पर्याप्त नहीं है; छोटे लेकिन व्यवस्थित प्रयास से भी सकारात्मक परिवर्तन लाया जा सकता है।`, question:"लगभग 80–100 शब्दों में लिखिए कि आरव की पहल में समस्या-समाधान की कौन-कौन-सी अवस्थाएँ दिखाई देती हैं। गद्यांश से कम-से-कम तीन अवस्थाएँ पहचानकर समझाइए।" },

// संस्कृत — ईशस्तुति + लोभविष्टः चक्रधरः
{ id:34, subject:"संस्कृत", type:"mcq", marks:1, question:"'ईशस्तुतिः' में स्तुति का मूल भाव किस विकल्प में सबसे ठीक व्यक्त होता है?", options:["ईश्वर के प्रति श्रद्धा और समर्पण","प्रतिस्पर्धा","उपेक्षा","क्रोध"], correct:0 },
{ id:35, subject:"संस्कृत", type:"mcq", marks:1, question:"'लोभविष्टः चक्रधरः' शीर्षक से ही चक्रधर के चरित्र की कौन-सी प्रमुख विशेषता का संकेत मिलता है?", options:["लोभ से प्रभावित होना","त्याग की भावना","भय का अभाव","विद्या के प्रति उदासीनता"], correct:0 },
{ id:36, subject:"संस्कृत", type:"mcq", marks:1, question:"'लोभविष्टः' का अर्थ समझने पर कथा के चरित्र के बारे में कौन-सा निष्कर्ष निकलता है?", options:["उसका व्यवहार लोभ से प्रभावित है","वह हमेशा निःस्वार्थ है","वह केवल विद्या चाहता है","वह किसी निर्णय से प्रभावित नहीं होता"], correct:0 },
{ id:37, subject:"संस्कृत", type:"mcq", marks:1, question:"कथा के संदेश के आधार पर लोभ और विवेक के संबंध को किस प्रकार समझना उचित है?", options:["अत्यधिक लोभ निर्णय-क्षमता को कमजोर कर सकता है","लोभ हमेशा सफलता देता है","विवेक का कोई महत्व नहीं","धन मिलने पर सभी निर्णय सही हो जाते हैं"], correct:0 },
{ id:38, subject:"संस्कृत", type:"mcq", marks:1, question:"यदि 'ईशस्तुतिः' के भाव को व्यवहार में उतारना हो, तो कौन-सा आचरण उसके सबसे निकट होगा?", options:["विनम्रता, श्रद्धा और समर्पण","अहंकार और उपेक्षा","ईर्ष्या और प्रतिस्पर्धा","केवल भौतिक लाभ की इच्छा"], correct:0 },
{ id:39, subject:"संस्कृत", type:"subjective", marks:4, question:"'लोभविष्टः चक्रधरः' के आधार पर स्पष्ट कीजिए कि लोभ किस प्रकार व्यक्ति के विवेकपूर्ण निर्णय को प्रभावित कर सकता है। कथा के संदेश को अपने शब्दों में लिखिए।" },
{ id:40, subject:"संस्कृत", type:"subjective", marks:4, question:"'ईशस्तुतिः' के आधार पर भक्त और ईश्वर के संबंध में श्रद्धा, विनम्रता तथा समर्पण के भाव को अपने शब्दों में स्पष्ट कीजिए।" },

// English — literature + unseen reading passage
{ id:41, subject:"English", type:"mcq", marks:1, question:"In 'I'm going to dance again', Sonal Mansingh's response to a serious setback is best understood as an example of:", options:["resilience and determination","fear-driven avoidance","dependence on easy success","rejection of her goal"], correct:0 },
{ id:42, subject:"English", type:"mcq", marks:1, question:"In 'Scaling Great Heights', Santosh Yadav's achievement is significant because it demonstrates that difficult goals can be pursued through:", options:["discipline, courage and sustained effort","luck without preparation","avoiding challenges","wealth alone"], correct:0 },
{ id:43, subject:"English", type:"mcq", marks:1, question:"In 'Dharam Juddha', Padma's struggle can best be understood as a struggle for:", options:["education, dignity and an independent sense of identity","wealth and political power","comfort without responsibility","business success"], correct:0 },
{ id:44, subject:"English", type:"mcq", marks:1, question:"In 'The Grandmother', the speaker's remembrance suggests that a person can remain emotionally present through:", options:["memory and sensory impressions","official documents only","scientific experiments","examination results"], correct:0 },
{ id:45, subject:"English", type:"mcq", marks:1, section:"Reading Comprehension", passage:`When Meera moved to a new town, she noticed that many students in her neighbourhood travelled a long distance to borrow books. Instead of simply complaining about it, she began collecting storybooks, magazines and old textbooks from families who no longer needed them. Every Sunday, she arranged the books in a small room near the community centre and kept a notebook to record which books were borrowed. At first, only a few children visited. Meera continued to invite them and asked older students to recommend books for younger readers. After several months, the room had become a lively reading corner. Meera learned that a useful idea does not become successful merely because it is good; it needs patience, organisation and the willingness to involve other people.`, question:"What can be inferred from Meera's decision to continue even when only a few children visited at first?", options:["She understood that useful change may require patience","She believed the project had already failed","She wanted to stop lending books","She cared only about keeping records"], correct:0 },
{ id:46, subject:"English", type:"mcq", marks:1, section:"Reading Comprehension", passage:`When Meera moved to a new town, she noticed that many students in her neighbourhood travelled a long distance to borrow books. Instead of simply complaining about it, she began collecting storybooks, magazines and old textbooks from families who no longer needed them. Every Sunday, she arranged the books in a small room near the community centre and kept a notebook to record which books were borrowed. At first, only a few children visited. Meera continued to invite them and asked older students to recommend books for younger readers. After several months, the room had become a lively reading corner. Meera learned that a useful idea does not become successful merely because it is good; it needs patience, organisation and the willingness to involve other people.`, question:"Which sequence best represents Meera's problem-solving process?", options:["identify problem → collect resources → organise → involve others → sustain","complain → stop → restart","buy everything → work alone → close","wait → ignore problem → succeed"], correct:0 },
{ id:47, subject:"English", type:"subjective", marks:4, question:"How does Sonal Mansingh's response to adversity illustrate resilience? Explain how her attitude and continued effort support this idea. Write about 80–100 words." },
{ id:48, subject:"English", type:"subjective", marks:4, section:"Reading Comprehension", passage:`When Meera moved to a new town, she noticed that many students in her neighbourhood travelled a long distance to borrow books. Instead of simply complaining about it, she began collecting storybooks, magazines and old textbooks from families who no longer needed them. Every Sunday, she arranged the books in a small room near the community centre and kept a notebook to record which books were borrowed. At first, only a few children visited. Meera continued to invite them and asked older students to recommend books for younger readers. After several months, the room had become a lively reading corner. Meera learned that a useful idea does not become successful merely because it is good; it needs patience, organisation and the willingness to involve other people.`, question:"In about 80–100 words, explain how Meera converted a local difficulty into a community solution. Identify two problem-solving qualities and support each with evidence from the passage." },

// Reasoning — conceptual number series
{ id:49, subject:"तार्किक क्षमता", type:"mcq", marks:1, question:"शृंखला पूरी करें: 2, 6, 12, 20, 30, ?", options:["40","42","44","46"], correct:1 },
{ id:50, subject:"तार्किक क्षमता", type:"mcq", marks:1, question:"शृंखला पूरी करें: 3, 8, 18, 38, 78, ?", options:["156","158","159","160"], correct:2 },
{ id:51, subject:"तार्किक क्षमता", type:"mcq", marks:1, question:"शृंखला पूरी करें: 121, 100, 81, 64, ?", options:["49","45","36","56"], correct:0 },
{ id:52, subject:"तार्किक क्षमता", type:"mcq", marks:1, question:"शृंखला पूरी करें: 2, 3, 5, 9, 17, ?", options:["25","31","33","35"], correct:2 },
{ id:53, subject:"तार्किक क्षमता", type:"mcq", marks:1, question:"शृंखला पूरी करें: 4, 9, 19, 39, 79, ?", options:["149","157","159","161"], correct:2 },

// अतिरिक्त उच्च-स्तरीय subjective
{ id:54, subject:"गणित", type:"subjective", marks:4, question:"दो संख्याओं का योग 7 और गुणनफल 10 है। इन्हें शून्यक मानकर एक द्विघात बहुपद बनाइए। फिर शून्यकों के योग और गुणनफल के सूत्रों से अपने उत्तर की जाँच कीजिए।" },
{ id:55, subject:"सामाजिक विज्ञान", type:"subjective", marks:4, question:"भारत के 82°30′E मानक मध्याह्न से 15° पूर्व स्थित स्थान के स्थानीय समय में लगभग कितना अंतर होगा? गणना सहित समझाइए कि पूर्व की ओर जाने पर स्थानीय समय क्यों आगे होता है और भारत के लिए मानक समय की आवश्यकता क्यों है।" }
];